/* ==========================================================================
   SGE_cre.sql
   Création du schéma relationnel du SGE (Système de Gestion d'Entrepôts).
   Corrections v2 :
     - Tous les identifiants sont VARCHAR(7) au format PPP0001 (3 lettres + 4 chiffres).
     - GENERATED BY DEFAULT AS IDENTITY remplacé par des séquences + DEFAULT.
     - produit_materiel.id_produit corrigé en VARCHAR(7).
     - lot.id_lot et inventaire_emplacement.id_lot unifiés en VARCHAR(7).
     - Clé primaire composite de REPERTOIRE corrigée (une seule clause PRIMARY KEY).
     - ENUM disponibilite sans accent (encodage portable).
     - Valeur 'reservee' absente de l'enum remplacée par la valeur correcte.
   Exécution : psql -f SGE_cre.sql
   ========================================================================== */

DROP SCHEMA IF EXISTS sge CASCADE;
CREATE SCHEMA sge;
SET search_path TO sge;

/* ── Domaines ─────────────────────────────────────────────────────────────── */

CREATE DOMAIN dom_nom AS varchar(50)
  CHECK (length(trim(VALUE)) > 0);

CREATE DOMAIN dom_telephone AS varchar(25)
  CHECK (VALUE IS NULL OR VALUE ~ '^[0-9 +().\-]{6,25}$');

CREATE DOMAIN dom_quantite AS integer
  CHECK (VALUE >= 0);

CREATE DOMAIN dom_mesure AS numeric(12,3)
  CHECK (VALUE >= 0);

/* ── Types énumérés ──────────────────────────────────────────────────────── */

CREATE TYPE sexe_type       AS ENUM ('F', 'M', 'X');
CREATE TYPE role_repertoire AS ENUM ('Responsable stocks', 'Responsable logistique', 'Agent logistique', 'Fournisseur', 'Magasinier', 'Responsable informatique', 'Administrateur', 'Livreur', 'Emballeur');
CREATE TYPE type_organisation AS ENUM ('Fournisseur', 'Transporteur', 'Destinataire', 'Partenaire');
CREATE TYPE type_colis      AS ENUM ('entrant', 'sortant');
CREATE TYPE type_produit    AS ENUM ('materiel', 'logiciel', 'emballage');
CREATE TYPE type_procede    AS ENUM ('reception', 'stockage', 'expedition', 'preparation', 'inventaire');
/* CORR: accent retiré de 'occupée' → 'occupee' pour portabilité d'encodage */
CREATE TYPE type_disponibilite AS ENUM ('libre', 'occupee', 'indisponible');

/* ── Séquences (une par table ayant un identifiant auto) ─────────────────── */

CREATE SEQUENCE seq_per  START 1 INCREMENT 1 NO CYCLE;
CREATE SEQUENCE seq_lot  START 1 INCREMENT 1 NO CYCLE;
CREATE SEQUENCE seq_prd  START 1 INCREMENT 1 NO CYCLE;
CREATE SEQUENCE seq_ent  START 1 INCREMENT 1 NO CYCLE;
CREATE SEQUENCE seq_zns  START 1 INCREMENT 1 NO CYCLE;
CREATE SEQUENCE seq_znr  START 1 INCREMENT 1 NO CYCLE;
CREATE SEQUENCE seq_zne  START 1 INCREMENT 1 NO CYCLE;
CREATE SEQUENCE seq_cel  START 1 INCREMENT 1 NO CYCLE;
CREATE SEQUENCE seq_col  START 1 INCREMENT 1 NO CYCLE;
CREATE SEQUENCE seq_chg  START 1 INCREMENT 1 NO CYCLE;
CREATE SEQUENCE seq_brc  START 1 INCREMENT 1 NO CYCLE;
CREATE SEQUENCE seq_bex  START 1 INCREMENT 1 NO CYCLE;
CREATE SEQUENCE seq_rap  START 1 INCREMENT 1 NO CYCLE;

/* Fonction utilitaire : génère un identifiant PPP0001 */
CREATE OR REPLACE FUNCTION gen_id(p_prefix text, p_seq regclass)
RETURNS varchar(7)
LANGUAGE sql STABLE AS $$
  SELECT p_prefix || LPAD(nextval(p_seq)::text, 4, '0');
$$;

/* ── Tables ──────────────────────────────────────────────────────────────── */

CREATE TABLE personnel (
  id_personnel       varchar(7)  PRIMARY KEY DEFAULT gen_id('PER', 'seq_per'),
  nom                dom_nom     NOT NULL,
  prenom             dom_nom     NOT NULL,
  sexe               sexe_type   NOT NULL,
  adresse            text,
  telephone          dom_telephone,
  date_naissance     date,
  date_enregistrement date       NOT NULL DEFAULT CURRENT_DATE,
  CHECK (date_naissance IS NULL OR date_naissance <= CURRENT_DATE)
);

/* CORR: REPERTOIRE — clé primaire composite déclarée une seule fois en fin de table */
CREATE TABLE externe (
  id_personnel  varchar(7) PRIMARY KEY
                  REFERENCES personnel(id_personnel) ON DELETE CASCADE,
  role_externe  dom_nom    NOT NULL,
  CHECK (role_externe IN ('Responsable stocks', 'Responsable logistique', 'Agent logistique', 'Fournisseur', 'Magasinier', 'Responsable informatique', 'Administrateur', 'Livreur', 'Emballeur'))
);

CREATE TABLE organisation (
  id_personnel  varchar(7)         PRIMARY KEY
                  REFERENCES personnel(id_personnel) ON DELETE CASCADE,
  type_org      type_organisation  NOT NULL
);

CREATE TABLE repertoire (
  id_organisation  varchar(7)      NOT NULL REFERENCES organisation(id_personnel) ON DELETE CASCADE,
  id_externe       varchar(7)      NOT NULL REFERENCES externe(id_personnel)      ON DELETE CASCADE,
  role             role_repertoire NOT NULL,
  PRIMARY KEY (id_organisation, id_externe)   -- CORR: une seule clause PRIMARY KEY composite
);

CREATE TABLE chargement (
  no_chargement   varchar(7)   PRIMARY KEY DEFAULT gen_id('CHG', 'seq_chg'),  -- CORR: varchar(7) + séquence
  livreur         varchar(7)   REFERENCES personnel(id_personnel) ON DELETE SET NULL,
  procede         type_procede NOT NULL,
  date_chargement timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE colis (
  no_colis        varchar(7)  PRIMARY KEY DEFAULT gen_id('COL', 'seq_col'),   -- CORR: varchar(7) + séquence
  no_chargement   varchar(7)  REFERENCES chargement(no_chargement) ON DELETE SET NULL,
  date_arrivee    timestamp,
  date_expedition timestamp,
  type            type_colis  NOT NULL
);

CREATE TABLE produit (
  id_produit      varchar(7)   PRIMARY KEY DEFAULT gen_id('PRD', 'seq_prd'),
  no_colis_origine varchar(7)  REFERENCES colis(no_colis) ON DELETE SET NULL,
  nom             dom_nom      NOT NULL,
  description     text,
  marque          dom_nom,
  modele          dom_nom,
  fournisseur     varchar(7)   REFERENCES organisation(id_personnel) ON DELETE SET NULL,
  type            type_produit NOT NULL
);

/* CORR: id_produit était INTEGER — doit être VARCHAR(7) pour référencer produit(id_produit) */
CREATE TABLE produit_materiel (
  id_produit  varchar(7)  PRIMARY KEY REFERENCES produit(id_produit) ON DELETE CASCADE,
  longueur    dom_mesure  NOT NULL,
  largeur     dom_mesure  NOT NULL,
  hauteur     dom_mesure  NOT NULL,
  masse       dom_mesure  NOT NULL
);

CREATE TABLE produit_logiciel (
  id_produit    varchar(7) PRIMARY KEY REFERENCES produit(id_produit) ON DELETE CASCADE,
  version       dom_nom    NOT NULL,
  description_log text,
  editeur       dom_nom,
  taille        dom_mesure
);

CREATE TABLE produit_emballage (
  id_produit  varchar(7) PRIMARY KEY REFERENCES produit(id_produit) ON DELETE CASCADE,
  nouveau     boolean    NOT NULL DEFAULT true
);

CREATE TABLE contenu_colis (
  no_colis    varchar(7)    NOT NULL REFERENCES colis(no_colis)     ON DELETE CASCADE,
  id_produit  varchar(7)    NOT NULL REFERENCES produit(id_produit) ON DELETE RESTRICT,
  qte_produit dom_quantite  NOT NULL,
  PRIMARY KEY (no_colis, id_produit)
);

/* CORR: id_lot était INTEGER GENERATED — doit être VARCHAR(7) avec séquence */
CREATE TABLE lot (
  id_lot      varchar(7)   PRIMARY KEY DEFAULT gen_id('LOT', 'seq_lot'),
  id_produit  varchar(7)   NOT NULL REFERENCES produit(id_produit) ON DELETE RESTRICT,
  quantite    dom_quantite NOT NULL
);

CREATE TABLE entrepot (
  no_entrepot    varchar(7)  PRIMARY KEY DEFAULT gen_id('ENT', 'seq_ent'),
  longueur       dom_mesure  NOT NULL,
  largeur        dom_mesure  NOT NULL,
  hauteur        dom_mesure  NOT NULL,
  masse_maximale dom_mesure  NOT NULL
);

CREATE TABLE zone_stockage (
  no_zs        varchar(7)  PRIMARY KEY DEFAULT gen_id('ZNS', 'seq_zns'),
  no_entrepot  varchar(7)  NOT NULL REFERENCES entrepot(no_entrepot) ON DELETE CASCADE,
  nom          dom_nom     NOT NULL,
  longueur     dom_mesure  NOT NULL,
  largeur      dom_mesure  NOT NULL,
  hauteur      dom_mesure  NOT NULL,
  position     dom_nom     NOT NULL,
  UNIQUE (no_entrepot, nom)
);

CREATE TABLE zone_reception (
  id_zone_reception  varchar(7) PRIMARY KEY DEFAULT gen_id('ZNR', 'seq_znr'),
  no_entrepot        varchar(7) NOT NULL REFERENCES entrepot(no_entrepot) ON DELETE CASCADE,
  nom                dom_nom    NOT NULL,
  role               dom_nom    NOT NULL,
  UNIQUE (no_entrepot, nom)
);

CREATE TABLE zone_expedition (
  id_zone_expedition  varchar(7) PRIMARY KEY DEFAULT gen_id('ZNE', 'seq_zne'),
  no_entrepot         varchar(7) NOT NULL REFERENCES entrepot(no_entrepot) ON DELETE CASCADE,
  nom                 dom_nom    NOT NULL,
  role                dom_nom    NOT NULL,
  UNIQUE (no_entrepot, nom)
);

CREATE TABLE cellule (
  no_cellule     varchar(7)          PRIMARY KEY DEFAULT gen_id('CEL', 'seq_cel'),
  no_zs          varchar(7)          NOT NULL REFERENCES zone_stockage(no_zs) ON DELETE CASCADE,
  disponibilite  type_disponibilite  NOT NULL DEFAULT 'libre',
  longueur       dom_mesure          NOT NULL,
  largeur        dom_mesure          NOT NULL,
  hauteur        dom_mesure          NOT NULL,
  masse_maximale dom_mesure          NOT NULL
);

/* CORR: id_lot est maintenant VARCHAR(7) pour être cohérent avec lot(id_lot) */
CREATE TABLE inventaire_emplacement (
  no_cellule      varchar(7)   NOT NULL REFERENCES cellule(no_cellule) ON DELETE CASCADE,
  id_lot          varchar(7)   NOT NULL REFERENCES lot(id_lot)         ON DELETE CASCADE,
  quantite_stockee dom_quantite NOT NULL,
  PRIMARY KEY (no_cellule, id_lot)
);

/* CORR: varchar(7) GENERATED BY DEFAULT AS IDENTITY est illégal en PostgreSQL.
         On utilise des séquences via DEFAULT gen_id(). */
CREATE TABLE bon_reception (
  id_bon_reception  varchar(7) PRIMARY KEY DEFAULT gen_id('BRC', 'seq_brc'),
  no_colis          varchar(7) NOT NULL UNIQUE REFERENCES colis(no_colis) ON DELETE CASCADE,
  description_recep text       NOT NULL
);

CREATE TABLE bon_expedition (
  id_bon_expedition varchar(7) PRIMARY KEY DEFAULT gen_id('BEX', 'seq_bex'),
  no_colis          varchar(7) NOT NULL UNIQUE REFERENCES colis(no_colis) ON DELETE CASCADE,
  description_exped text       NOT NULL
);

CREATE TABLE rapport_exception (
  id_rapport          varchar(7)   PRIMARY KEY DEFAULT gen_id('RAP', 'seq_rap'),
  no_chargement       varchar(7)   REFERENCES chargement(no_chargement) ON DELETE SET NULL,
  no_colis            varchar(7)   REFERENCES colis(no_colis)           ON DELETE SET NULL,
  description_rapport text         NOT NULL,
  procede             type_procede NOT NULL,
  date_rapport        timestamp    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (no_chargement IS NOT NULL OR no_colis IS NOT NULL)
);

/* ── Index ───────────────────────────────────────────────────────────────── */

CREATE INDEX idx_produit_nom       ON produit(nom);
CREATE INDEX idx_lot_produit       ON lot(id_produit);
CREATE INDEX idx_inventaire_lot    ON inventaire_emplacement(id_lot);
CREATE INDEX idx_cellule_zone      ON cellule(no_zs);
CREATE INDEX idx_colis_type        ON colis(type);
CREATE INDEX idx_colis_chargement  ON colis(no_chargement);


