/* SGE_cre.sql

   Ce script crée les domaines, les types énumérés, les tables déduits du MCD.

   C'est la création du schéma relationnel du SGE
 */

 DROP SCHEMA IF EXISTS sge CASCADE;
CREATE SCHEMA sge;
SET search_path TO sge;

CREATE DOMAIN dom_nom AS varchar(50)
CHECK(length(trim(VALUE)) > 0);

CREATE DOMAIN dom_telephone AS varchar(25)
CHECK(VALUE IS NULL or VALUE ~ '^[0-9 +().-]{6,25}$');

CREATE DOMAIN dom_quantite AS INTEGER
CHECK( VALUE >= 0);

CREATE DOMAIN dom_mesure AS numeric(12,3)
CHECK(VALUE >= 0 );

CREATE TYPE sexe_type AS ENUM ('F','M','X');
CREATE TYPE role_repertoire AS ENUM ('Conducteur', 'Magasinier', 'acheteur','vendeur');
CREATE TYPE type_organisation AS ENUM ('Fournisseur', 'Transporteur', 'destinataire', 'partenaire');
CREATE TYPE type_colis AS ENUM ('entrant', 'sortant');
CREATE TYPE type_produit AS ENUM ('materiel','logiciel', 'emballage');
CREATE TYPE type_procede AS ENUM ('reception','stockage','expedition','preparation','inventaire');
CREATE TYPE disponibilite AS ENUM ('libre', 'occupée','indisponible');


CREATE TABLE Personnel (
    id_personnel varchar(7) PRIMARY KEY,
    nom dom_nom NOT NULL,
    prenom dom_nom NOT NULL,
    sexe sexe_type NOT NULL,
    adresse text,
    telephone dom_telephone,
    date_naissance date,
    date_enregistrement date NOT NULL DEFAULT CURRENT_DATE,
    CHECK( date_naissance IS NULL or date_naissance <= CURRENT_DATE)
);

CREATE TABLE externe (
    id_personnel varchar(7) PRIMARY KEY REFERENCES Personnel(id_personnel) ON DELETE CASCADE,
    role_externe dom_nom NOT NULL
);

CREATE TABLE organisation (
    id_personnel varchar(7) PRIMARY KEY REFERENCES Personnel(id_personnel) ON DELETE CASCADE,
    type_org type_organisation NOT NULL
);

CREATE TABLE repertoire (
    id_organisation varchar(7) not null primary key REFERENCES organisation(id_personnel) ON DELETE CASCADE,
    id_externe varchar(7) not null primary key references externe(id_personnel) ON DELETE CASCADE,
    role role_repertoire not null primary key
);

CREATE TABLE chargement (
  no_chargement integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  livreur varchar(7) REFERENCES personnel(id_personnel) ON DELETE SET NULL,
  procede type_procede NOT NULL,
  date_chargement timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE colis (
  no_colis integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  no_chargement integer REFERENCES chargement(no_chargement) ON DELETE SET NULL,
  date_arrivee timestamp,
  date_expedition timestamp,
  type type_colis NOT NULL
);

CREATE TABLE produit (
  id_produit varchar(7) PRIMARY KEY,
  no_colis_origine integer REFERENCES colis(no_colis) ON DELETE SET NULL,
  nom dom_nom NOT NULL,
  description text,
  marque dom_nom,
  modele dom_nom,
  fournisseur varchar(7) REFERENCES organisation(id_personnel) ON DELETE SET NULL,
  type type_produit NOT NULL
);

CREATE TABLE produit_materiel (
  id_produit integer PRIMARY KEY REFERENCES produit(id_produit) ON DELETE CASCADE,
  longueur dom_mesure NOT NULL,
  largeur dom_mesure NOT NULL,
  hauteur dom_mesure NOT NULL,
  masse dom_mesure NOT NULL
);

CREATE TABLE produit_logiciel (
  id_produit varchar(7) PRIMARY KEY REFERENCES produit(id_produit) ON DELETE CASCADE,
  version dom_nom NOT NULL,
  description_log text,
  editeur dom_nom,
  taille dom_mesure
);

CREATE TABLE produit_emballage (
  id_produit varchar(7) PRIMARY KEY REFERENCES produit(id_produit) ON DELETE CASCADE,
  nouveau boolean NOT NULL DEFAULT true
);

CREATE TABLE contenu_colis (
  no_colis integer NOT NULL REFERENCES colis(no_colis) ON DELETE CASCADE,
  id_produit varchar(7) NOT NULL REFERENCES produit(id_produit) ON DELETE RESTRICT,
  qte_produit dom_quantite NOT NULL,
  PRIMARY KEY (no_colis, id_produit)
);

CREATE TABLE lot (
  id_lot integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_produit varchar(7) NOT NULL REFERENCES produit(id_produit) ON DELETE RESTRICT,
  quantite dom_quantite NOT NULL
);

CREATE TABLE entrepot (
  no_entrepot integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  longueur dom_mesure NOT NULL,
  largeur dom_mesure NOT NULL,
  hauteur dom_mesure NOT NULL,
  masse_maximale dom_mesure NOT NULL
);

CREATE TABLE zone_stockage (
  no_zs integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  no_entrepot integer NOT NULL REFERENCES entrepot(no_entrepot) ON DELETE CASCADE,
  nom dom_nom NOT NULL,
  longueur dom_mesure NOT NULL,
  largeur dom_mesure NOT NULL,
  hauteur dom_mesure NOT NULL,
  position dom_nom NOT NULL,
  UNIQUE (no_entrepot, nom)
);

CREATE TABLE zone_reception (
  id_zone_reception integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  no_entrepot integer NOT NULL REFERENCES entrepot(no_entrepot) ON DELETE CASCADE,
  nom dom_nom NOT NULL,
  role dom_nom NOT NULL,
  UNIQUE (no_entrepot, nom)
);

CREATE TABLE zone_expedition (
  id_zone_expedition integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  no_entrepot integer NOT NULL REFERENCES entrepot(no_entrepot) ON DELETE CASCADE,
  nom dom_nom NOT NULL,
  role dom_nom NOT NULL,
  UNIQUE (no_entrepot, nom)
);

CREATE TABLE cellule (
  no_cellule integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  no_zs integer NOT NULL REFERENCES zone_stockage(no_zs) ON DELETE CASCADE,
  disponibilite disponibilite NOT NULL DEFAULT 'libre',
  longueur dom_mesure NOT NULL,
  largeur dom_mesure NOT NULL,
  hauteur dom_mesure NOT NULL,
  masse_maximale dom_mesure NOT NULL,
  UNIQUE (no_zs, no_cellule)
);

CREATE TABLE inventaire_emplacement (
  no_cellule integer NOT NULL REFERENCES cellule(no_cellule) ON DELETE CASCADE,
  id_lot varchar(7) NOT NULL REFERENCES lot(id_lot) ON DELETE CASCADE,
  quantite_stockee dom_quantite NOT NULL,
  PRIMARY KEY (no_cellule, id_lot)
);

CREATE TABLE bon_reception (
  id_bon_reception  varchar(7) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  no_colis integer NOT NULL UNIQUE REFERENCES colis(no_colis) ON DELETE CASCADE,
  description_recep text NOT NULL
);

CREATE TABLE bon_expedition (
  id_bon_expedition varchar(7) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  no_colis integer NOT NULL UNIQUE REFERENCES colis(no_colis) ON DELETE CASCADE,
  description_exped text NOT NULL
);

CREATE TABLE rapport_exception (
  id_rapport varchar(7) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  no_chargement integer REFERENCES chargement(no_chargement) ON DELETE SET NULL,
  no_colis integer REFERENCES colis(no_colis) ON DELETE SET NULL,
  description_rapport text NOT NULL,
  procede type_procede NOT NULL,
  date_rapport timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (no_chargement IS NOT NULL OR no_colis IS NOT NULL)
);

CREATE INDEX idx_produit_nom ON produit(nom);
CREATE INDEX idx_lot_produit ON lot(id_produit);
CREATE INDEX idx_inventaire_lot ON inventaire_emplacement(id_lot);
CREATE INDEX idx_cellule_zone ON cellule(no_zs);
